### ISSUE TITLE
Master build is broken

### ISSUE THREAD

**Issue by myuwono** [kotest/kotest-extensions-arrow#239]
Master build is currently failing with this error

```
> Task :commonizeNativeDistribution FAILED

> Task :kotest-assertions-arrow:compileCommonMainKotlinMetadata
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':commonizeNativeDistribution'.
> Could not resolve all files for configuration ':kotlinKlibCommonizerClasspath'.
   > Cannot resolve external dependency org.jetbrains.kotlin:kotlin-klib-commonizer-embeddable:1.8.10 because no repositories are defined.
     Required by:
         project :

```

**Comment by Kantis** [comment]
Fixed by [53ae245](https://github.com/kotest/kotest-extensions-arrow/pull/240/commits/53ae245e704a61625aa8feea22b95b59518c9301). For some reason Kotlin 1.7+ seems to register the `kotlinKlibCommonizerClasspath` task on the root project, even if that project is not a Kotlin project. Adding repositories in the root `build.gradle.kts` was what solved it.
